scan_filter_chain:
- name: angle
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: 0
    upper_angle: 3.14

- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    use_message_range_limits: false
    upper_threshold: .inf
    #has to be lower than reported maxrange!
    upper_replacement_value: 7.9

#- type: laser_filters/LaserArrayFilter
 # name: laser_median_filter
  #params: 
   # range_filter_chain:
    #  - name: median_5
     #   type: filters/MultiChannelMedianFilterFloat 
      #  params:
       #   number_of_observations: 2
        #  unused: 10
    #intensity_filter_chain:
     # - name: median_5
      #  type: filters/MultiChannelMedianFilterFloat 
       # params:
        #  number_of_observations: 2
         # unused: 10